spring.application.name: myreads-preload-data

datadump.location:
  authors: myreads-preload-data/src/main/resources/test_authors_dump.txt
  books: myreads-preload-data/src/main/resources/test_books_dump.txt   

spring: 
  data:
    cassandra:
      keyspace-name: main
      username: MBeaRZcunOPYTihbNkyUyUJP
      password: _Ejhga-tbAQZhCWZ0sg95,KR2b__0_uRctwKCEWQkfh,SZYqYW6+z3yWJ6o8cMNAuy3nF360QRKLaPCg5Mk6TsjhctXeeL_RsrIrCSd6JkJZ_5kAexR-Wq,1vD1BIp6q
      request:
        timeout: 10s
      schema-action: recreate
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra.secure-connect-bundle: secure-connect-myreadsdb.zip

astra:
  db: 
    id: 5ece3807-c3ae-4b01-a16a-bad3eaa16d90-1
    region: eu-central-1
    keyspace-name: main
    application.token: AstraCS:MBeaRZcunOPYTihbNkyUyUJP:4066f232c36aabd8fc1a4774294c05850530990edb71441ccbf1d20358371c82
